# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  newrelic:
    image: newrelic
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5089:5089
    environment:
      - ASPNETCORE_ENVIRONMENT=Developmenet
